pages:
  image: node
  before_script:
    - cd instruction_page
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run generate
    - echo "Listing output folder:"
    - ls -la .output/public
  artifacts:
    paths:
      - instruction_page/.output/public
  publish: instruction_page/.output/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - instruction_page/.npm/

